spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shangting?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
minio:
  endpoint: http://150.158.140.21:9000
  access-key: admin
  secret-key: admin123
  bucket-name: shangting
